version: '3.7'

services:

  mongo:
    image: mongo
    container_name: bassoon_mongo
    restart: always
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: bassoon_db
      MONGO_INITDB_ROOT_USERNAME: bassoon_user
      MONGO_INITDB_ROOT_PASSWORD: bassoon_password
